### ISSUE TITLE
just gives normal dashboard even when installed?

### ISSUE THREAD

**Issue by AyashiNoCeres** [kthready/gdb_tmux#1]
I'm a bit confused how to use this...i've installed everything but when i run gdb it just give the normal dashboard?

How do i get it to do it in tmux with the split windows?

*edit*
Ah silly me, when you said "Run debug" you literally meant run the file debug in the repo, not just run gdb!

**Comment by kthready** [comment]
@AyashiNoCeres have you resolved the issue?
